services:
  letta_db:
    image: ankane/pgvector:v0.5.1
    networks:
      default:
        aliases:
          - pgvector_db
          - letta-db
    environment:
      - POSTGRES_USER=${LETTA_PG_USER:-letta}
      - POSTGRES_PASSWORD=${LETTA_PG_PASSWORD:-letta}
      - POSTGRES_DB=${LETTA_PG_DB:-letta}
    volumes:
      - ./.persist/pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  letta_server:
    image: lettaai/letta:latest
    hostname: letta
    depends_on:
      - letta_db
    networks:
      - default
    ports:
      - "8083:8083"
      - "8283:8283"
    env_file:
      - stack.env  # Portainer to load read stack environment variables and create this file
    environment:
      - LETTA_PG_DB=${LETTA_PG_DB:-letta}
      - LETTA_PG_USER=${LETTA_PG_USER:-letta}
      - LETTA_PG_PASSWORD=${LETTA_PG_PASSWORD:-letta}
      - LETTA_PG_HOST=pgvector_db
      - LETTA_PG_PORT=5432
      - LETTA_DEBUG=True
      - LETTA_LLM_MODEL=${LETTA_LLM_MODEL}
      - LETTA_EMBEDDING_ENDPOINT_TYPE=${LETTA_EMBEDDING_ENDPOINT_TYPE}
      - LETTA_EMBEDDING_MODEL=${LETTA_EMBEDDING_MODEL}
      - OPENAI_API_KEY=${ENV_OPENAI_API_KEY}

  letta_nginx:
    hostname: letta-nginx
    image: nginx:stable-alpine3.17-slim
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - default
    ports:
      - "80:80"

networks:
  default:
    driver: bridge # Plans for isolated swarm network to come later 🤞
